/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AbhyasRouteImport } from './routes/abhyas'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ExamTodayRouteImport } from './routes/exam-today'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbhyasRoute = AbhyasRouteImport.update({
  id: '/abhyas',
  path: '/abhyas',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamTodayRoute = ExamTodayRouteImport.update({
  id: '/exam-today',
  path: '/exam-today',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abhyas': typeof AbhyasRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-today': typeof ExamTodayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mistakes': typeof MistakesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRouteWithChildren
  '/result': typeof ResultRoute
  '/revision': typeof RevisionRoute
  '/super-admin': typeof SuperAdminRoute
  '/register/success': typeof RegisterSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abhyas': typeof AbhyasRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-today': typeof ExamTodayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mistakes': typeof MistakesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRouteWithChildren
  '/result': typeof ResultRoute
  '/revision': typeof RevisionRoute
  '/super-admin': typeof SuperAdminRoute
  '/register/success': typeof RegisterSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abhyas': typeof AbhyasRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-today': typeof ExamTodayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mistakes': typeof MistakesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRouteWithChildren
  '/result': typeof ResultRoute
  '/revision': typeof RevisionRoute
  '/super-admin': typeof SuperAdminRoute
  '/register/success': typeof RegisterSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abhyas'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/exam'
    | '/exam-today'
    | '/leaderboard'
    | '/login'
    | '/mistakes'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/register'
    | '/result'
    | '/revision'
    | '/super-admin'
    | '/register/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abhyas'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/exam'
    | '/exam-today'
    | '/leaderboard'
    | '/login'
    | '/mistakes'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/register'
    | '/result'
    | '/revision'
    | '/super-admin'
    | '/register/success'
  id:
    | '__root__'
    | '/'
    | '/abhyas'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/exam'
    | '/exam-today'
    | '/leaderboard'
    | '/login'
    | '/mistakes'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/register'
    | '/result'
    | '/revision'
    | '/super-admin'
    | '/register/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbhyasRoute: typeof AbhyasRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ExamRoute: typeof ExamRoute
  ExamTodayRoute: typeof ExamTodayRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MistakesRoute: typeof MistakesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ResultRoute: typeof ResultRoute
  RevisionRoute: typeof RevisionRoute
  SuperAdminRoute: typeof SuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/abhyas': {
      id: '/abhyas'
      path: '/abhyas'
      fullPath: '/abhyas'
      preLoaderRoute: typeof AbhyasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-today': {
      id: '/exam-today'
      path: '/exam-today'
      fullPath: '/exam-today'
      preLoaderRoute: typeof ExamTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterSuccessRoute: typeof RegisterSuccessRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSuccessRoute: RegisterSuccessRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbhyasRoute: AbhyasRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ExamRoute: ExamRoute,
  ExamTodayRoute: ExamTodayRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MistakesRoute: MistakesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ResultRoute: ResultRoute,
  RevisionRoute: RevisionRoute,
  SuperAdminRoute: SuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
